### PR TITLE
fixed a bug in delete action

### PR DESCRIPTION
**Pull request by Mourad-Ouerghi**

### CODE REVIEW

**Comment by ComfortablyCoding** [comment]
Can you please comment on what case this is covering? It is not so clear to me.

**Comment by Mourad-Ouerghi** [comment]
In fact I saved a publish action then I wanted to delete it, after pressing the delete button I got a 404 error then I checked the logs and saw the request was default to id = 0 when I replaced it with that code, the delete button worked

**Comment by ComfortablyCoding** [comment]
What version of the plugin are you using? I cannot replicate this issue.

**Comment by Mourad-Ouerghi** [comment]
I wasn't using the latest version I updated the version and it works now

**Pull request closed without merging**
